[CmdletBinding()]
param(
    [switch]$NonInteractive,
    [string]$NodePath,
    [string]$MaterialsStudioRoot,
    [string]$WorkRoot,
    [string]$ModelRoot,
    [string]$RemoteSshTarget,
    [string]$RemoteJobsRoot,
    [int]$DashboardPort = 4877
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
$configDir = Join-Path $repoRoot 'config'
New-Item -ItemType Directory -Force -Path $configDir | Out-Null

function Find-Node {
    if ($NodePath) { return [IO.Path]::GetFullPath($NodePath) }
    $sibling = Join-Path (Split-Path -Parent $repoRoot) 'nodejs\node.exe'
    if (Test-Path -LiteralPath $sibling) { return $sibling }
    $command = Get-Command node.exe -ErrorAction SilentlyContinue
    if ($command) { return $command.Source }
    return 'C:\Program Files\nodejs\node.exe'
}

function Find-MaterialsStudio {
    if ($MaterialsStudioRoot) { return [IO.Path]::GetFullPath($MaterialsStudioRoot) }
    if ($env:MS_INSTALL_ROOT) { return [IO.Path]::GetFullPath($env:MS_INSTALL_ROOT) }
    $candidates = New-Object System.Collections.Generic.List[string]
    foreach ($drive in (Get-PSDrive -PSProvider FileSystem -ErrorAction SilentlyContinue)) {
        foreach ($relative in @('Program Files\BIOVIA', 'Program Files (x86)\BIOVIA')) {
            $biovia = Join-Path $drive.Root $relative
            if (-not (Test-Path -LiteralPath $biovia)) { continue }
            Get-ChildItem -LiteralPath $biovia -Directory -ErrorAction SilentlyContinue |
                Where-Object Name -Like 'Materials Studio*' |
                ForEach-Object { $candidates.Add($_.FullName) }
        }
    }
    $match = $candidates | Where-Object { Test-Path -LiteralPath (Join-Path $_ 'etc\Scripting\bin\RunMatScript.bat') } | Select-Object -First 1
    if ($match) { return $match }
    return 'C:\Program Files\BIOVIA\Materials Studio'
}

function Ask([string]$Label, [string]$Default, [bool]$AllowEmpty = $false) {
    if ($NonInteractive) { return $Default }
    $suffix = if ($Default) { " [$Default]" } else { '' }
    do {
        $answer = Read-Host "$Label$suffix"
        if ([string]::IsNullOrWhiteSpace($answer)) { $answer = $Default }
    } while (-not $AllowEmpty -and [string]::IsNullOrWhiteSpace($answer))
    return $answer
}

function BatchValue([string]$Value) {
    if ($null -eq $Value) { return '' }
    return $Value.Replace('%', '%%').Replace('"', '')
}

function TomlValue([string]$Value) {
    if ($null -eq $Value) { return '' }
    return $Value.Replace('\', '\\').Replace('"', '\"')
}

Write-Host 'MS-MCP local configuration' -ForegroundColor Cyan
Write-Host 'Press Enter to accept a detected/default value. Paths are validated before files are written.'

$node = Ask '1/8 Node.js executable' (Find-Node)
$npm = Join-Path (Split-Path -Parent $node) 'npm.cmd'
$msRoot = Ask '2/8 BIOVIA Materials Studio install root' (Find-MaterialsStudio)
$defaultWork = Join-Path (Split-Path -Parent $repoRoot) 'MS-MCP-Workspace'
$workspace = Ask '3/8 Writable MS-MCP workspace' $(if ($WorkRoot) { $WorkRoot } else { $defaultWork })
$policy = Ask '4/8 Structure policy: auto, manual, or require_cif_first' 'auto'
$portText = Ask '5/8 Dashboard TCP port' ([string]$DashboardPort)
$model = Ask '6/8 Existing Materials Studio model folder (optional)' $ModelRoot $true
$sshTarget = Ask '7/8 Remote SSH target user@host (optional)' $RemoteSshTarget $true
$jobsRoot = Ask '8/8 Remote Gateway jobs folder (optional)' $RemoteJobsRoot $true

$node = [IO.Path]::GetFullPath($node)
$msRoot = [IO.Path]::GetFullPath($msRoot)
$workspace = [IO.Path]::GetFullPath($workspace)
$runMatScript = Join-Path $msRoot 'etc\Scripting\bin\RunMatScript.bat'
$parsedPort = 0

if (-not (Test-Path -LiteralPath $node -PathType Leaf)) { throw "Node.js was not found: $node" }
if (-not (Test-Path -LiteralPath $npm -PathType Leaf)) { throw "npm.cmd was not found beside node.exe: $npm" }
if (-not (Test-Path -LiteralPath $runMatScript -PathType Leaf)) { throw "RunMatScript.bat was not found. MS_INSTALL_ROOT must be the folder containing etc\Scripting: $msRoot" }
if (@('auto', 'manual', 'require_cif_first') -notcontains $policy) { throw "Invalid structure policy: $policy" }
if (-not [int]::TryParse($portText, [ref]$parsedPort) -or $parsedPort -lt 1 -or $parsedPort -gt 65535) { throw "Invalid Dashboard port: $portText" }
New-Item -ItemType Directory -Force -Path $workspace | Out-Null

$sshKey = Join-Path $env:USERPROFILE '.ssh\id_ed25519_ms_mcp'
$batLines = @(
    '@echo off',
    'rem Generated by Configure-MS-MCP.bat. Re-run that file instead of editing unless documented.',
    ('set "NODE_EXE={0}"' -f (BatchValue $node)),
    ('set "NPM_CMD={0}"' -f (BatchValue $npm)),
    ('set "MS_INSTALL_ROOT={0}"' -f (BatchValue $msRoot)),
    ('set "MS_MCP_WORK_ROOT={0}"' -f (BatchValue $workspace)),
    ('set "MS_MCP_QUEUE_DIR={0}"' -f (BatchValue (Join-Path $workspace '.mcp-queue'))),
    ('set "MS_MCP_STRUCTURE_SOURCE_POLICY={0}"' -f $policy),
    'set "MS_MCP_ALLOW_ARBITRARY_SCRIPT=0"',
    'set "MS_MCP_ALLOW_GUI_QUEUE=1"',
    'set "MS_MCP_ALLOW_EXTERNAL_INPUTS=0"',
    'set "MS_MCP_ALLOWED_CIF_HOSTS=www.crystallography.net,crystallography.net"',
    'set "MS_MCP_MAX_CIF_BYTES=10485760"',
    ('set "MS_MCP_DASHBOARD_PORT={0}"' -f $parsedPort),
    'set "MS_MCP_DASHBOARD_AUTOSTART=1"',
    'set "MS_MCP_DASHBOARD_AUTO_OPEN=0"',
    'set "MS_MCP_DASHBOARD_WRITE=0"',
    ('set "MS_MCP_MODEL_ROOT={0}"' -f (BatchValue $model)),
    ('set "MS_MCP_REMOTE_SSH_TARGET={0}"' -f (BatchValue $sshTarget)),
    ('set "MS_MCP_REMOTE_SSH_KEY={0}"' -f (BatchValue $sshKey)),
    ('set "MS_MCP_REMOTE_JOBS_ROOT={0}"' -f (BatchValue $jobsRoot))
)

$tomlLines = @(
    '# Generated by Configure-MS-MCP.bat. Copy this block into %USERPROFILE%\.codex\config.toml.',
    '[mcp_servers.MS-MCP]',
    ('command = "{0}"' -f (TomlValue $node)),
    ('args = ["{0}"]' -f (TomlValue (Join-Path $repoRoot 'src\index.js'))),
    ('cwd = "{0}"' -f (TomlValue $repoRoot)),
    'startup_timeout_sec = 20',
    'tool_timeout_sec = 1800',
    'default_tools_approval_mode = "prompt"',
    '',
    '[mcp_servers.MS-MCP.env]',
    ('MS_INSTALL_ROOT = "{0}"' -f (TomlValue $msRoot)),
    ('MS_MCP_WORK_ROOT = "{0}"' -f (TomlValue $workspace)),
    ('MS_MCP_STRUCTURE_SOURCE_POLICY = "{0}"' -f $policy),
    'MS_MCP_ALLOW_ARBITRARY_SCRIPT = "0"',
    'MS_MCP_ALLOW_GUI_QUEUE = "1"',
    'MS_MCP_ALLOW_EXTERNAL_INPUTS = "0"',
    'MS_MCP_ALLOWED_CIF_HOSTS = "www.crystallography.net,crystallography.net"',
    'MS_MCP_MAX_CIF_BYTES = "10485760"',
    ('MS_MCP_DASHBOARD_PORT = "{0}"' -f $parsedPort),
    'MS_MCP_DASHBOARD_AUTOSTART = "1"',
    'MS_MCP_DASHBOARD_AUTO_OPEN = "0"'
)
if ($model) { $tomlLines += ('MS_MCP_MODEL_ROOT = "{0}"' -f (TomlValue ([IO.Path]::GetFullPath($model)))) }
if ($sshTarget) { $tomlLines += ('MS_MCP_REMOTE_SSH_TARGET = "{0}"' -f (TomlValue $sshTarget)) }
if ($sshTarget) { $tomlLines += ('MS_MCP_REMOTE_SSH_KEY = "{0}"' -f (TomlValue $sshKey)) }
if ($jobsRoot) { $tomlLines += ('MS_MCP_REMOTE_JOBS_ROOT = "{0}"' -f (TomlValue $jobsRoot)) }

$utf8 = New-Object Text.UTF8Encoding($false)
$batFile = Join-Path $configDir 'ms-mcp.local.bat'
$tomlFile = Join-Path $configDir 'codex-ms-mcp.local.toml'
[IO.File]::WriteAllLines($batFile, $batLines, $utf8)
[IO.File]::WriteAllLines($tomlFile, $tomlLines, $utf8)

Write-Host "`nGenerated:" -ForegroundColor Green
Write-Host "  $batFile"
Write-Host "  $tomlFile"
Write-Host "`nPaths that must be changed after moving this repository: NODE_EXE, MS_INSTALL_ROOT, MS_MCP_WORK_ROOT, and the command/args/cwd lines in Codex config. The safe method is to re-run Configure-MS-MCP.bat."
